[[questions]]
type = "MultipleChoice"
prompt.prompt = """
El arbol resultante, ¿es equilibrado?
"""
prompt.distractors = [
	"No"
]
answer.answer = "Sí"

context = """
El árbol resultante es el siguiente que, claramente, es equilibrado:

![Árbol equilibrado de altura 3](08_3/Arbol1.png)
"""
id = "a874b4c6-1ffb-437a-9be6-641c9eb86c4c"

[[questions]]
type = "MultipleChoice"
prompt.prompt = """
Tras la pregunta anterior deberías haber obtenido el siguiente árbol:

![Árbol equilibrado de altura 3](08_3/Arbol1.png)

Si hacemos un recorrido en inorden de ese árbol. ¿Qué secuencia obtenemos?
"""
prompt.distractors = [
	"1, 2, 3, 5, 6, 7, 4",
	"4, 2, 6, 1, 3, 5, 7",
	"4, 2, 1, 3, 6, 5, 7"
]
answer.answer = "1, 2, 3, 4, 5, 6, 7"
id = "a0139663-fb5f-4476-ab38-36687ba65071"



